### ISSUE TITLE
signFromFile return null

### ISSUE THREAD

**Issue by jeanechabaudis** [thegreenter/xmldsig#1]
I'm doing the example of the README.md and at the moment of executing the method signFromFile returns a null value and does not sign the xml

this my code:

use Greenter\XMLSecLibs\Sunat\SignedXml;

require 'vendor/autoload.php';

$xmlPath = '20516109549-01-F001-70.xml';
$certPath = 'certificate.pem'; // Convertir pfx to pem 

$signer = new SignedXml();
$signer->setCertificateFromFile($certPath);

$xmlSigned = $signer->signFromFile($xmlPath);

var_dump($xmlSigned);

**Comment by giansalex** [comment]
Fixed, thanks.

**Comment by jeanechabaudis** [comment]
I'm still receiving null, xml attachment and code


[signed.zip](https://github.com/giansalex/xmldsig/files/1802890/signed.zip)

**Comment by giansalex** [comment]
- You need to convert `cert.pfx` -> `cert.pem`, tutorial [here](https://github.com/giansalex/xmldsig/blob/master/CONVERT.md#convert-to-pem)
- Use xmldsig v5.0.1 in `composer.json`

**Comment by jeanechabaudis** [comment]
if it is converted and keeps returning null, I attach the arvhivo .pem
[certificate.zip](https://github.com/giansalex/xmldsig/files/1803143/certificate.zip)

**Comment by jeanechabaudis** [comment]
Sorry it was my mistake, I just had to update the package with composer but the X509SubjectName tag does not have to be something similar

`<X509SubjectName>E=rubenmedinag@hotmail.com, CN=AGUILAR APONTE DE ARAUCO CONSTANTINA VILMA, OU=DNI 20053183 RUC 20516109549, OU=DNI 20053183 RUC 20516109549, O=INVERSIONES DEL VALLE EIRL, L=LIMA, S=ATE, C=PE</X509SubjectName>`

**Comment by giansalex** [comment]
X509SubjectName is not required. That is an additional information.
`ds:X509Data/ds:X509Certificate` contains that information.

**Comment by jeanechabaudis** [comment]
Okay thanks for your help :D
